### PR TITLE
Proposal: Style tray display to be more in line with GNOME tray icons

### PR DESCRIPTION
**Pull request by Mershl**
Hi Tyler,

You moved the tray icon to the left. This is a proposal to move it to the right and style the source/provider icon to be more in line with other GNOME tray icons.

### CODE REVIEW

**Comment by jylertones** [comment]
Hi Mershl, appreciate the pull request! At the time, I quite intentionally put the tray icon on the left. For me, my music is one of my most important running apps. I'll give this code a try and see how I like it.

**Comment by Mershl** [comment]
I think I understand your thought in keeping it on the left. On higher resolutions it may be easier to spot the track on the top left, while on smaller resolutions the tray section on the right might fill up too fast with a long song+artist combination.

We could offer this change as an **alternative** to keep the styling more in line with the usual Gnome tray extension.

**Comment by jylertones** [comment]
I've been running it for a couple of days now, and I'm not entirely sure I like it better. I'm going to sit on this one for a little and see if I like it better, or if I can tweak it to improve in some way on the right side.

**Comment by jylertones** [comment]
This is a long time down the road, but I'm going to merge this. I've been running this way since June and it works great. I just needed some time to adapt. Thank you @Mershl

**Pull request merged**
